/* This file is generated by mscbMakeCode.exe */

#ifndef MSCB_PWRSWITCH_2200_h
#define MSCB_PWRSWITCH_2200_h


struct PWRSWITCH_2200_bank {
   uint32_t _timestamp;
   uint8_t  _protocol_version;
   uint8_t  _n_variables;
   uint16_t _node_address;
   uint16_t _group_address;
   uint16_t _svn_revision;
   uint8_t  shutdown; //   0 Shutdown   unit  52, prefix   0, status 0, flags 0
   uint8_t  control ; //   1 Control    unit  52, prefix   0, status 0, flags 0
   uint8_t  status  ; //   2 Status     unit  52, prefix   0, status 0, flags 0
   uint8_t  pad1;
   float    in_volt1; //   3 in Volt1   unit  24, prefix   0, status 0, flags 1
   float    in_volt2; //   4 in Volt2   unit  24, prefix   0, status 0, flags 1
   float    in_volt3; //   5 in Volt3   unit  24, prefix   0, status 0, flags 1
   float    outvolt1; //   6 outVolt1   unit  24, prefix   0, status 0, flags 1
   float    outvolt2; //   7 outVolt2   unit  24, prefix   0, status 0, flags 1
   float    outvolt3; //   8 outVolt3   unit  24, prefix   0, status 0, flags 1
   float    outvolt4; //   9 outVolt4   unit  24, prefix   0, status 0, flags 1
   float    outvolt5; //  10 outVolt5   unit  24, prefix   0, status 0, flags 1
   float    outvolt6; //  11 outVolt6   unit  24, prefix   0, status 0, flags 1
   float    outcur1 ; //  12 outcur1    unit   6, prefix   0, status 0, flags 1
   float    outcur2 ; //  13 outCur2    unit   6, prefix   0, status 0, flags 1
   float    outcur3 ; //  14 outCur3    unit   6, prefix   0, status 0, flags 1
   float    outcur4 ; //  15 outCur4    unit   6, prefix   0, status 0, flags 1
   float    outcur5 ; //  16 outCur5    unit   6, prefix   0, status 0, flags 1
   float    outcur6 ; //  17 outCur6    unit   6, prefix   0, status 0, flags 1
   float    temp1   ; //  18 Temp1      unit   8, prefix   0, status 0, flags 1
   float    temp2   ; //  19 Temp2      unit   8, prefix   0, status 0, flags 1
   float    temp3   ; //  20 Temp3      unit   8, prefix   0, status 0, flags 1
   float    temp4   ; //  21 Temp4      unit   8, prefix   0, status 0, flags 1
   float    temp5   ; //  22 Temp5      unit   8, prefix   0, status 0, flags 1
   float    temp6   ; //  23 Temp6      unit   8, prefix   0, status 0, flags 1
   float    intemp1 ; //  24 inTemp1    unit   8, prefix   0, status 0, flags 1
   float    intemp2 ; //  25 inTemp2    unit   8, prefix   0, status 0, flags 1
   float    intemp3 ; //  26 inTemp3    unit   8, prefix   0, status 0, flags 1
   float    ltemp1  ; //  27 LTemp1     unit   8, prefix   0, status 0, flags 1
   float    ltemp2  ; //  28 LTemp2     unit   8, prefix   0, status 0, flags 1
   float    ltemp3  ; //  29 LTemp3     unit   8, prefix   0, status 0, flags 1
   float    ltemp4  ; //  30 LTemp4     unit   8, prefix   0, status 0, flags 1
   float    ltemp5  ; //  31 LTemp5     unit   8, prefix   0, status 0, flags 1
   float    ltemp6  ; //  32 LTemp6     unit   8, prefix   0, status 0, flags 1
};

#define PWRSWITCH_2200_BUFSIZE         123
#define PWRSWITCH_2200_NODE_NAME       "PWRSWITCH"
#define PWRSWITCH_2200_SVN_REVISION    2200
#define PWRSWITCH_2200_NUM_VARS         33
#define PWRSWITCH_2200_SHUTDOWN     0
#define PWRSWITCH_2200_CONTROL      1
#define PWRSWITCH_2200_STATUS       2
#define PWRSWITCH_2200_IN_VOLT1     3
#define PWRSWITCH_2200_IN_VOLT2     4
#define PWRSWITCH_2200_IN_VOLT3     5
#define PWRSWITCH_2200_OUTVOLT1     6
#define PWRSWITCH_2200_OUTVOLT2     7
#define PWRSWITCH_2200_OUTVOLT3     8
#define PWRSWITCH_2200_OUTVOLT4     9
#define PWRSWITCH_2200_OUTVOLT5    10
#define PWRSWITCH_2200_OUTVOLT6    11
#define PWRSWITCH_2200_OUTCUR1     12
#define PWRSWITCH_2200_OUTCUR2     13
#define PWRSWITCH_2200_OUTCUR3     14
#define PWRSWITCH_2200_OUTCUR4     15
#define PWRSWITCH_2200_OUTCUR5     16
#define PWRSWITCH_2200_OUTCUR6     17
#define PWRSWITCH_2200_TEMP1       18
#define PWRSWITCH_2200_TEMP2       19
#define PWRSWITCH_2200_TEMP3       20
#define PWRSWITCH_2200_TEMP4       21
#define PWRSWITCH_2200_TEMP5       22
#define PWRSWITCH_2200_TEMP6       23
#define PWRSWITCH_2200_INTEMP1     24
#define PWRSWITCH_2200_INTEMP2     25
#define PWRSWITCH_2200_INTEMP3     26
#define PWRSWITCH_2200_LTEMP1      27
#define PWRSWITCH_2200_LTEMP2      28
#define PWRSWITCH_2200_LTEMP3      29
#define PWRSWITCH_2200_LTEMP4      30
#define PWRSWITCH_2200_LTEMP5      31
#define PWRSWITCH_2200_LTEMP6      32

const char* PWRSWITCH_2200_InitStr[] = {
   "[.]",
   "_timestamp = DWORD",
   "_protocol_version = BYTE",
   "_n_variables = BYTE",
   "_node_address = WORD",
   "_group_address = WORD",
   "_svn_revision = WORD",
   "shutdown   = BYTE",
   "control    = BYTE",
   "status     = BYTE",
   "pad1       = BYTE",
   "in_volt1   = FLOAT",
   "in_volt2   = FLOAT",
   "in_volt3   = FLOAT",
   "outvolt1   = FLOAT",
   "outvolt2   = FLOAT",
   "outvolt3   = FLOAT",
   "outvolt4   = FLOAT",
   "outvolt5   = FLOAT",
   "outvolt6   = FLOAT",
   "outcur1    = FLOAT",
   "outcur2    = FLOAT",
   "outcur3    = FLOAT",
   "outcur4    = FLOAT",
   "outcur5    = FLOAT",
   "outcur6    = FLOAT",
   "temp1      = FLOAT",
   "temp2      = FLOAT",
   "temp3      = FLOAT",
   "temp4      = FLOAT",
   "temp5      = FLOAT",
   "temp6      = FLOAT",
   "intemp1    = FLOAT",
   "intemp2    = FLOAT",
   "intemp3    = FLOAT",
   "ltemp1     = FLOAT",
   "ltemp2     = FLOAT",
   "ltemp3     = FLOAT",
   "ltemp4     = FLOAT",
   "ltemp5     = FLOAT",
   "ltemp6     = FLOAT",
   NULL
};

static void PWRSWITCH_2200_copy(void*xbank, int xbank_size, uint32_t time, const MSCB_INFO* info, const char* data) {
   PWRSWITCH_2200_bank* bank = (PWRSWITCH_2200_bank*)xbank;
   bank->_timestamp = time;
   bank->_protocol_version = info->protocol_version;
   bank->_n_variables   = info->n_variables;
   bank->_node_address  = info->node_address;
   bank->_group_address = info->group_address;
   bank->_svn_revision  = info->svn_revision;
   u8be2local(&bank->shutdown, data+0);
   u8be2local(&bank->control, data+1);
   u8be2local(&bank->status, data+2);
   bank->pad1 = 0;
   u32be2local(&bank->in_volt1, data+3);
   u32be2local(&bank->in_volt2, data+7);
   u32be2local(&bank->in_volt3, data+11);
   u32be2local(&bank->outvolt1, data+15);
   u32be2local(&bank->outvolt2, data+19);
   u32be2local(&bank->outvolt3, data+23);
   u32be2local(&bank->outvolt4, data+27);
   u32be2local(&bank->outvolt5, data+31);
   u32be2local(&bank->outvolt6, data+35);
   u32be2local(&bank->outcur1, data+39);
   u32be2local(&bank->outcur2, data+43);
   u32be2local(&bank->outcur3, data+47);
   u32be2local(&bank->outcur4, data+51);
   u32be2local(&bank->outcur5, data+55);
   u32be2local(&bank->outcur6, data+59);
   u32be2local(&bank->temp1, data+63);
   u32be2local(&bank->temp2, data+67);
   u32be2local(&bank->temp3, data+71);
   u32be2local(&bank->temp4, data+75);
   u32be2local(&bank->temp5, data+79);
   u32be2local(&bank->temp6, data+83);
   u32be2local(&bank->intemp1, data+87);
   u32be2local(&bank->intemp2, data+91);
   u32be2local(&bank->intemp3, data+95);
   u32be2local(&bank->ltemp1, data+99);
   u32be2local(&bank->ltemp2, data+103);
   u32be2local(&bank->ltemp3, data+107);
   u32be2local(&bank->ltemp4, data+111);
   u32be2local(&bank->ltemp5, data+115);
   u32be2local(&bank->ltemp6, data+119);
}

#endif
/* end */
